# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6369, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AnalyzedBusinessCard
    from ._models_py3 import AnalyzedBusinessCardFields
    from ._models_py3 import AnalyzedForm
    from ._models_py3 import AnalyzedPassport
    from ._models_py3 import AnalyzedPassportFormFields
    from ._models_py3 import DateFormField
    from ._models_py3 import DictionaryFormField
    from ._models_py3 import FormField
    from ._models_py3 import ListFormField
    from ._models_py3 import NumberFormField
    from ._models_py3 import StringFormField
except (SyntaxError, ImportError):
    from ._models import AnalyzedBusinessCard  # type: ignore
    from ._models import AnalyzedBusinessCardFields  # type: ignore
    from ._models import AnalyzedForm  # type: ignore
    from ._models import AnalyzedPassport  # type: ignore
    from ._models import AnalyzedPassportFormFields  # type: ignore
    from ._models import DateFormField  # type: ignore
    from ._models import DictionaryFormField  # type: ignore
    from ._models import FormField  # type: ignore
    from ._models import ListFormField  # type: ignore
    from ._models import NumberFormField  # type: ignore
    from ._models import StringFormField  # type: ignore

from ._body_polymorphic_enums import (
    Value,
)

__all__ = [
    'AnalyzedBusinessCard',
    'AnalyzedBusinessCardFields',
    'AnalyzedForm',
    'AnalyzedPassport',
    'AnalyzedPassportFormFields',
    'DateFormField',
    'DictionaryFormField',
    'FormField',
    'ListFormField',
    'NumberFormField',
    'StringFormField',
    'Value',
]
