parameters:
  "service-dir":
    default: "sdk/openai"
  "dependencies":
    default: ""
emit: [
  "@azure-tools/typespec-python",
]
options:
  "@azure-tools/typespec-python":
    package-mode: "dataplane"
    package-dir: "azure-openai"
    package-name: "azure-openai"
